### ISSUE TITLE
test fails on master branch

### ISSUE THREAD

**Issue by ryanking** [coinbase/toshi#153]
I just downloaded, setup and ran the tests for the first time. There was one failure:

Failures:

  1) TheBlueMatt BitcoindComparisonTool should complete successfully
     Failure/Error: expect(regtest_thr.value.exitstatus).to eq(0)
       
       expected: 0
            got: 1
       
       (compared using ==)
     # ./spec/toshi/regression_spec.rb:50:in `block (3 levels) in <top (required)>'
     # ./spec/toshi/regression_spec.rb:46:in `block (2 levels) in <top (required)>'

**Comment by ryanking** [comment]
Derp. My fault.

**Comment by ryanking** [comment]
I take that back. I though this was just a user error, but it is not.

It appears that the jar file is not in the repo, all tests will fail.

**Comment by aalness** [comment]
Hey @ryanking sorry for the late reply but you need to initialize the submodule.

<code><pre>
$ git submodule init
$ git submodule update
</pre></code>
