### ISSUE TITLE
testnet3.toshi.io seems to be stuck

### ISSUE THREAD

**Issue by roneilr** [coinbase/toshi#156]
The testnet toshi node is reporting block height 320507 for the latest block (https://testnet3.toshi.io/api/v0/blocks/latest), but the actual latest block is ~320689 right now (see http://tbtc.blockr.io/).

**Comment by Matadoer** [comment]
bitcoin and litecoin main nodes are also "stuck"

**Comment by roneilr** [comment]
testnet3.toshi.io seems to be fixed now too, but it looks like it was stuck for quite a while. Anyone know why this could happen?

**Comment by roneilr** [comment]
Also, transactions broadcast during the "stuck" period don't seem to be rebroadcast after the system comes back online. A transaction I submitted to the public Toshi daemon had been sitting in the memory pool for a few days with 0 confirmations, with Toshi returning "{'error': 'transaction already received'}" when I attempted to rebroadcast it. However, the transaction was immediately broadcast and converted soon after I submitted it to blockchain.info's broadcast transaction page.

**Comment by chevdor** [comment]
It seems to be stuck again. We are now stuck at block 333044 since 2015-04-14 12:52:31 UTC.

This is probably due to the large amount of blocks being mined atm due to the difiiculty reset (https://blog.blocktrail.com/2015/04/in-the-darkest-depths-of-testnet3-16k-blocks-were-found-in-1-day/).

**Comment by aalness** [comment]
Right. The big reorg triggered a bug in toshi's block downloader. It's syncing again now. For details and status please see/watch: https://github.com/coinbase/toshi/pull/184

**Comment by aalness** [comment]
Fix was merged.
