### ISSUE TITLE
toshi COMPLETELY STOP syncing at  block 322083, with SSD and high-end CPU

### ISSUE THREAD

**Issue by feeling4t** [coinbase/toshi#162]
Hi,

I built toshi on ubuntu server 14.04, and I have a 512GB SSD so I put the whole ubuntu and db on the SSD. 
It has sync for 8days, work well.  BUT it sop sync at 8hours ago, at block 322082, with 299GB database.

I checked the log of redis and postgresql, no error. 
SSD still have 100GB free space.

Before, when it work well, has 120% cpu use and thousand IOPS, but now it only has little cpu use and IO.

My setting:

production:
  database_url: <%= ENV['DATABASE_URL']  || 'postgres://toshiuser:password@127.0.0.1:5432/toshi_db' %>
  log_level: <%= ENV['LOG_LEVEL'] || 'info' %>
  max_peers: 8
  network: <%= ENV['TOSHI_NETWORK'] || 'bitcoin' %>
  peers: <%= ENV['TOSHI_PEERS'].to_s.split(';') %>
  redis_url: <%= ENV['REDIS_URL'] || ENV['REDISTOGO_URL'] || ENV['OPENREDIS_URL']  || 'redis://127.0.0.1:6379/2' %>

and use 
export TOSHI_ENV=production
foreman start

run it

and I can see many warnning like this 

14:28:49 transaction_worker.1 | 2015-02-12T06:28:49.890Z 1298 TID-ow3cvprq0 Toshi::Workers::TransactionWorker JID-bbac62d7144147aaa11fd769 WARN: AcceptToMemoryPool() : transaction missing inputs
14:28:49 transaction_worker.1 | 2015-02-12T06:28:49.890Z 1298 TID-ow3cvprq0 Toshi::Workers::TransactionWorker JID-bbac62d7144147aaa11fd769 INFO: 
14:28:49 transaction_worker.1 | 2015-02-12T06:28:49.890Z 1298 TID-ow3cvprq0 Toshi::Workers::TransactionWorker JID-bbac62d7144147aaa11fd769 INFO: done: 0.015 sec
14:28:49 transaction_worker.1 | 2015-02-12T06:28:49.953Z 1298 TID-ow3cvprq0 Toshi::Workers::TransactionWorker JID-609cf077a057c46a7fa51a86 INFO: start
14:28:49 transaction_worker.1 | 2015-02-12T06:28:49.977Z 1298 TID-ow3cvprq0 Toshi::Workers::TransactionWorker JID-609cf077a057c46a7fa51a86 WARN: AcceptToMemoryPool() : transaction missing inputs
14

**Comment by DarthAndroid** [comment]
If I recall correctly, this block contains a transaction that activates the SSL bug that hit bitcoin core 0.9.3. Perhaps something similar is happening to Toshi?

**Comment by aalness** [comment]
Hey @feeling4t, have you tried syncing toshi lately? Still stuck?

**Comment by feeling4t** [comment]
@aalness I completely resync it again, from block 0, a few days ago
Guess what happen today ? 
IT  COMPLETELY STOP AT BLOCK 322083 AGAIN!

**Comment by feeling4t** [comment]
@DarthAndroid 
I clone the latest code, fix this problem
