### ISSUE TITLE
Guys, you can use Bitcoin bootstrap.dat instead of pg_dump bootstrap torrent

### ISSUE THREAD

**Issue by feeling4t** [coinbase/toshi#167]
I see bootstrap.rb in toshi code, and I tried it, it works.
Since I never find documents about it, and many guys ask for a pg_dump bootstrap torrent, so I post It here.

export BOOTSTRAP_FILE=/storage/bootstrap.dat 
export TOSHI_ENV=production
cd toshi/
bin/bootstrap.rb

**Comment by DoctorBit** [comment]
Cool, how long did it take?

**Comment by csquared** [comment]
https://github.com/coinbase/toshi/pull/169/files Should address this. Thoughts?

**Comment by csquared** [comment]
Got merged - going to close.
