### ISSUE TITLE
FATAL:  database "toshi_development" does not exist

### ISSUE THREAD

**Issue by chevdor** [coinbase/toshi#181]
Hello,

This is probably just an issue in the doc. I followed the installation instructions to run toshi locally using docker and I get the following message:
````FATAL:  database "toshi_development" does not exist````

I attached the logs.

[start_log.txt | uploaded via ZenHub](https://files.zenhub.io/552a3ef56568b7061480c55d)

**Comment by hudon** [comment]
Under "Running Toshi locally", there is a database creation step before you launch the system. What do you get when you run those commands?
```
$ docker-compose build
$ docker-compose start db
$ docker-compose run web bundle exec rake db:create
```

**Comment by chevdor** [comment]
Hi, 
I guess I missed the ```docker-compose run web bundle exec rake db:create```step.
Strange thing, I tried again and this command failed the first time.
A second run of the command did succeed and now everything works.
Very cool stuff! Thanks for your help. I close the ticket.

If someone would run into the same issue, make sure you did run ```docker-compose run web bundle exec rake db:create```and if you do, check that it does not return an error. If it does, a second try may help.
