### ISSUE TITLE
Why is there a `branch` column in the outputs table?

### ISSUE THREAD

**Issue by olalonde** [coinbase/toshi#187]
I noticed that toshi saves the branch of outputs. https://github.com/coinbase/toshi/blob/8181be4dfdba13d556c62d73a962f4fa1afd24e1/lib/toshi/models/output.rb#L24

Since this information can be inferred by going back to the transaction -> blocks chain, is this for performance reasons? Something else? Is this field updated on reorgs?

Sorry for the questions, I'm trying to understand the internals.

**Comment by aalness** [comment]
Yes, it's primarily for performance and yes it's updated on reorgs. The code that updates it on reorg is in the `BlockchainStorage` class. See methods mark_outputs_as*

**Comment by olalonde** [comment]
Thanks!
