### ISSUE TITLE
Testnet BlcokTime is wrong

### ISSUE THREAD

**Issue by assafshomer** [coinbase/toshi#193]
![toshitime](https://cloud.githubusercontent.com/assets/2572475/7608320/f720bf82-f970-11e4-91d0-1e0c2d3bed26.png)

**Comment by aalness** [comment]
Timestamps from the block header are often not very precise. See: https://en.bitcoin.it/wiki/Block_timestamp. Look at the `created_at` field to see the time Toshi created the block in its db: https://testnet3.toshi.io/api/v0/blocks/396513

**Comment by assafshomer** [comment]
Hi Andy.
I wasn't worried about not being totally precise, but about being [two hours](https://testnet3.toshi.io/api/v0/blocks/396513) into the future :). I didn't realize that a two hours shift is actually possible by design. Thanks for pointing [this](https://en.bitcoin.it/wiki/Block_timestamp.) out .
