### ISSUE TITLE
How to access SQL data?

### ISSUE THREAD

**Issue by igorbarinov** [coinbase/toshi#198]
Sorry for a noob question but how can I access SQL data?
How to connect to PSQL containter

**Comment by igorbarinov** [comment]
up, can't figure it out. please help

**Comment by andylamb** [comment]
```
docker exec -it toshi_db_1 psql -U postgres -d toshi_development
```
worked for me.

**Comment by igorbarinov** [comment]
@andylamb thanks, it worked for me too!
