### ISSUE TITLE
Lagging behind blockchain.info by 200 blocks

### ISSUE THREAD

**Issue by nubis** [coinbase/toshi#203]
Hi guys, it seems the demo toshi is having a hard time confirming transactions: https://bitcoin.toshi.io/
My own toshi instance shows the same behaviour. I'm looking into it but I guess you may be able to pinpoint the issue quicker than me.

While I investigate I'm increasing RAM and CPU power to my instance to see if that has anything to do with it.

Cheers!

**Comment by nubis** [comment]
Small update: Toshi and blockchain.info seem to have forked at block 	364923, a really long orphaned chain in my toshi database looks exactly like what blockchain.info is reporting as the current main branch.

**Comment by nubis** [comment]
Hi guys, I see https://bitcoin.toshi.io is now syncing again, did you just rebuild from a backup before block 364923? I didn't have any backups before that due to my backup retention, so now I'm syncing a new instance from scratch while I mess around with my existing database to see if I get either to catch up from block 364922 and on. Thanks for sharing :)

**Comment by lian** [comment]
thanks for the report.

fixed in https://github.com/coinbase/toshi/commit/f7083d6df65fade61d586b860f8b2058005aec80

**Comment by lian** [comment]
if it doesn't catchup, try this, i remember doing this while debugging.

    n = Models::Block.where(hsh: '000000000000000010dc318d201ad5fedf50c1de9b45196947d56af8a9ad2aa3').first
    p n 
    blk = Bitcoin::P::Block.new([`curl -s https://bitcoin.toshi.io/api/v0/blocks/000000000000000010dc318d201ad5fedf50c1de9b45196947d56af8a9ad2aa3.hex`].pack("H*"))
    Toshi::Models::RawBlock.create(hsh: blk.hash, payload: Sequel.blob(blk.to_payload))

and then restart the peer_manager

**Comment by nubis** [comment]
Awesome, thanks!
