### ISSUE TITLE
Multiple (different) blocks at the same height.

### ISSUE THREAD

**Issue by dan-da** [coinbase/toshi#207]
I'm not sure how serious this is. (seems bad)   I am seeing multiple blocks with the same height but different values.

I'm seeing this on both testnet and mainnet.  values below are from testnet, and the system has been started stopped many times during the initial sync.  So it may be related to that.

<pre>
toshi_development=# select height, count(*) from blocks group by height having count(*) > 1;          
 height | count 
--------+-------
      0 |    16
      1 |    11
      2 |     8
      3 |     8
      4 |     8
      5 |     6
      6 |     6
      7 |     5
      8 |     5
      9 |     5
     10 |     5
     11 |     5
     12 |     3
     13 |     3
     14 |     3
     15 |     2
     16 |     2
     17 |     2
     18 |     2
     19 |     2
     20 |     2
     21 |     2
     22 |     2
     23 |     2
     24 |     2
     25 |     2
     26 |     2
     27 |     2
     28 |     2
     29 |     2
     30 |     2
     31 |     2
     32 |     2
     33 |     2
(34 rows)
</pre>

So let's look at the blocks stored for one of these heights.  Notice they are different values.

<pre>
toshi_development=# select * from blocks where height = 33;
-[ RECORD 1 ]------+-----------------------------------------------------------------
id                 | 8724
hsh                | 00000000000312846cd887f35a945e637fc67cdae7aae8cb261289899f8f2a3f
height             | 33
prev_block         | 0000000000028136225c01f8002f6ba53c6a201e478230873e72b4c57309308f
mrkl_root          | bab7664fb59aadeed6ddbec118526450e9775c0fd9052aaa4344a08b8e999559
time               | 1438670203
bits               | 453193372
nonce              | 3240797680
ver                | 3
branch             | 2
size               | 1435
work               | \x50736991318a
fees               | 0
total_in_value     | 0
total_out_value    | 0
transactions_count | 6
created_at         | 2015-08-04 04:50:42.226754
-----   D 2 ]------+--------------------------------------------------------------More--
id                 | 34
hsh                | 00000000663742a962be4db62757e0464a83583c0f5abd74832ba35a3e5571f5
height             | 33
prev_block         | 00000000a8c3af05dadff24b9798dd317191645f45bb46c99d4bedd84705604c
mrkl_root          | 1c6991d08e16b64f1e0401c48a34b7b096e3a99b7b77b047182111a6c41ab0e5
time               | 1296691918
bits               | 486604799
nonce              | 3076553219
ver                | 1
branch             | 0
size               | 190
work               | \x2200220022
fees               | 0
total_in_value     | 0
total_out_value    | 5000000000
transactions_count | 1
created_at         | 2015-08-04 02:13:46.995818
</pre>

**Comment by aalness** [comment]
the blockchain is really a tree. what matters is that there is only one block at a specific height for the main branch (branch = 0.)

**Comment by dan-da** [comment]
thanks for the explanation.  that makes sense, and it seems the main branch is ok (no height dups) on both systems.

<pre>
toshi_production=# select branch, height, count(*) from blocks where branch=0 group by branch, height having count(*) > 1;
(No rows)
</pre>

<pre>
toshi_development=# select branch, height, count(*) from blocks where branch=0 group by branch, height having count(*) > 1;
(No rows)
</pre>

I guess I was most surprised by the dup behavior because I was was watching block timestamps while the system syncs and most of them are old ( 2011 ) and regularly increasing but a few are from today, and those were having very low block heights.   example:

<pre>
toshi_production=# select *, to_timestamp(time) from blocks order by time desc limit 1;
-[ RECORD 1 ]------+-----------------------------------------------------------------
id                 | 146330
hsh                | 000000000000000008ecdea402de551ad97f2cc3dccc94db0b9a725cb70c47ca
height             | 2
prev_block         | 000000000000000002db87a199d74a61ff46030e746a89e2aed6e9c819e48bc8
mrkl_root          | cab8d73e8a22fde755e4147078e1eb78a7f90650954176e15a7d3afb63be2613
time               | 1438802166
bits               | 404031509
nonce              | 1729073477
ver                | 3
branch             | 2
size               | 998132
work               | \x0c2c13cc6163da184d
fees               | 0
total_in_value     | 0
total_out_value    | 0
transactions_count | 1747
created_at         | 2015-08-05 19:22:18.103425
to_timestamp       | 2015-08-05 19:16:06+00
</pre>

I guess those are orphans, but I don't understand why the height is so low?

maybe it is just calculating the height as an offset from the block where it forked?

**Comment by aalness** [comment]
It's still getting current blocks from the network as they are announced while it syncs. Those will be orphans until you eventually sync the parent blocks. The heights there will be relative to the first orphan and aren't super useful. They'll be updated when they get connected to the main branch.

**Comment by dan-da** [comment]
ok, that makes sense.   So I guess when each block loads it also checks to see if any orphans reference it, and if so then it updates them.   ok, cool.   I'll go ahead and close this.

btw, I didn't see mentioned in the README... what's the best place to discuss Toshi, ask questions how it works, etc?
