### ISSUE TITLE
Does toshi depend on bitcoind?

### ISSUE THREAD

**Issue by redsquirrel** [coinbase/toshi#227]
I'm digging into toshi's [PeerManager](https://github.com/coinbase/toshi/blob/master/lib/toshi/peer_manager.rb) and [ConnectionHandler](https://github.com/coinbase/toshi/blob/master/lib/toshi/connection_handler.rb) and trying to understand how they're connecting to the Bitcoin network. Does toshi rely on a bitcoind to be running locally?

**Comment by redsquirrel** [comment]
(Sorry if this is a stupid question/issue.)

**Comment by redsquirrel** [comment]
Actually, I can see that it doesn't depend on bitcoind ... I was misunderstanding (this line](https://github.com/coinbase/toshi/blob/master/lib/toshi/peer_manager.rb#L101) ... but I still don't understand how it's hooking into the Bitcoin network. I'll keep digging. :construction_worker:

**Comment by aalness** [comment]
That's if you want to accept incoming connections which isn't enabled by default. It's mainly used to allow for `regtest` to run against it. It uses DNS seeds just like bitcoind to find peers and connect to them: https://github.com/coinbase/toshi/blob/8493464813dd1d0aebfd3b78ee7500cbbea26dc8/lib/toshi/models/peer.rb#L15-L25

**Comment by redsquirrel** [comment]
@aalness thanks! :raised_hands:
